### ISSUE TITLE
동일 API의 사용자 인증 / 서비스간 인증 방식 적용에 대해서

### ISSUE THREAD

**Issue by kyungmi** [ridi/style-guide#101]
아래에서 말하는 **사용자 인증**은 기존 세션 사용 방식 + [내부 서비스간의 SSO](https://github.com/ridi/style-guide/blob/master/API.md#%EB%82%B4%EB%B6%80-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-sso) 를,
**서비스간 인증**은 [신뢰할 수 있는 서비스간의 인가](https://github.com/ridi/style-guide/blob/master/API.md#%EC%8B%A0%EB%A2%B0%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8A%94-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-%EC%9D%B8%EA%B0%80inter-service-authorization)를 뜻합니다.

### 1. 동일 API가 여러 인증 방식을 적용해야 하는 경우
뷰어팀 API 중 동일한 작업을 하지만 **사용자 인증(=내부 서비스 간의 SSO)**/**서비스간 인증(신뢰할 수 있는 서비스간의 인가)**이 각각 필요한 것이 있는데요. (참고: https://app.asana.com/0/637011828394799/770740400334179/f)

API 중 `/user-devices`의 경우 현재까지는 사용자 인증을 통해 디바이스를 조회했지만, 이제 서비스간 인증으로도 동작하도록 구현해야 합니다.

(1) 엔드포인트를 두 가지로 구분해야 할지,
(2) 하나의 엔드포인트에서 두개의 인증 방식을 우선순위를 두어 처리해야 할지
가 고민입니다.

만약에 (1)을 선택하게 되었을때 엔드포인트 네이밍 룰에 대해서도 조금 고민이 되고요.

혹시 동일한 문제가 있었고, 해결하신 분이 있는지 궁금한데요.
그게 아니더라도 좋은 해결책이 있다면 답변 부탁드립니다~

### 2. API의 인증 방식 결정 기준
추가적인 질문입니다.
각 팀에서 API의 인증 방식(사용자 인증, 서비스간 인증)을 결정할 때의 기준은 무엇인가요? 서비스의 백엔드에서 호출하느냐, 프론트엔드에서 호출하느냐 정도의 차이일까요?

프론트엔드에서 호출하더라도 자기 자신의 백엔드를 프록싱해서 사용하는 경우 서비스간 호출로 봐야 하는 것일까요?
그렇게 볼 수 있다면, (조금 과장해서) 현재까지의 모든 API들은 (3rd party에 노출되지 않는 이상에는) 서비스간 호출에만 사용된다고 볼 수 있는데, 이 부분도 어떻게 생각하시는지 궁금합니다.

**Comment by earus** [comment]
@kyungmi 

의견에 앞서 궁금한 사항이 있는데요~

(1) 사용자 인증 = 세션에 기반한 인증을 의미하는게 맞나요?
(2) 인증 방식을 서비스간 인증으로 통일할 수 없는 이유가 있는건가요?

**Comment by kyungmi** [comment]
@earus 
(1) 네 맞습니다. 세션에 기반한 인증 + OAuth2 인증을 포함해서요.
(2) 일단 디바이스 목록 조회/디바이스 조회 기능의 경우에는 아직까지 Ajax 방식으로 동작하는 곳이 없고, 제가 알기로는 (아직 API를 직접 호출하지는 않지만) 스토어팀, 플랫폼팀에서 사용중인 것으로 알고 있습니다. 사용처에서 인증 방식을 바꿔주신다면 별 다른 문제는 없겠지만 다른 `/user-devices` 를 프리픽스로 가지는 API들과 인증 방식에 있어서 일관성이 없어진다는 문제가 있습니다.

이정도에서 갑자기 궁금해지는데요. 
각 팀에서 API의 인증 방식(사용자 인증, 서비스간 인증)을 결정할 때의 기준은 무엇인가요? 서비스의 백엔드에서 호출하느냐, 프론트엔드에서 호출하느냐 정도의 차이일까요?
프론트엔드에서 호출하더라도 자기 자신의 백엔드를 프록싱해서 사용하는 경우 서비스간 호출로 봐야 하는 것일까요?
그렇게 볼 수 있다면, 현재까지의 모든 API들은 (3rd party에 노출되지 않는 이상에는) 서비스간 호출에만 사용된다고 볼 수 있는데, 이 부분도 어떻게 생각하시는지 궁금합니다. 
질문에 함께 적어 놓을게요~

**Comment by kyungmi** [comment]
다시 스타일 가이드를 보니 오해의 여지가 있을 것 같네요.
제가 말씀드린 사용자 인증은 [내부 서비스간의 SSO](https://github.com/ridi/style-guide/blob/master/API.md#%EB%82%B4%EB%B6%80-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-sso) 를 말씀드린 것이고요.
서비스간 인증이 [신뢰할 수 있는 서비스간의 인가](https://github.com/ridi/style-guide/blob/master/API.md#%EC%8B%A0%EB%A2%B0%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8A%94-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-%EC%9D%B8%EA%B0%80inter-service-authorization)입니다.

**Comment by antiline** [comment]
@kyungmi 
2. API의 인증 방식 결정 기준

1)
모든 케이스를 아래와 같이 나눌 수 없지만, 
유저의 행동으로 시작되는건 사용자 인증, 시스템 행동으로 시작되는건 서비스간 인증
으로 해야 한다고 생각합니다.

2)
`/user-devices` API는 사용자 인증이나 서비스간 인증 둘다 요청, 응답 모양이 서로 같나요?????

그에 따라서 특별한 경우가 아니라면 요청, 응답 모양이 서로 다르다고 생각되는데요.
예를 들어서 사용자 인증 을 통한 API는 u_idx 같은 정보가 요청에 들어가지 않기 때문에 해당 API 에 서비스간 인증을 붙일 수 없다고 생각됩니다.

**Comment by kyungmi** [comment]
플랫폼팀에서 요청하신 디바이스 조회 API의 서비스간 인증은 사용자의 요청에 의해 발생되지만, 로그인 세션 없이 진행되는 작업이라 특수한 경우에 해당합니다.
더 이상 논의가 진행되지 않고 있고, 현재 뷰어 API를 위한 도메인이 분화되지 않은 상태에서 path prefix 등을 추가하는 것은 무리가 있다(프록시 설정 등의 인프라 업데이트 작업이 수반되기 떄문에)고 판단되어, 저 스스로는 아직 사용처가 없는 /user-devices API는 일단 **서비스간 인증만을 지원**하고, 나중에 **필요해질 경우 동일 엔드포인트에서 사용자 인증을 함께 진행**하는 것으로 하는 것이 좋을 것 같다는 결론을 내렸습니다.
이 이슈는 닫을게요~
