### ISSUE TITLE
[mysql] composite primary 키는 사용하지 않나요?

### ISSUE THREAD

**Issue by pueue** [ridi/style-guide#106]
문서에는 컬럼명이 정해진 단일 컬럼만 명시되어 있는데, composite primary 키를 사용하지 않는 이유가 궁금합니다.

**Comment by namenu** [comment]
Composite primary key를 사용하려는 이유가 무엇인가요?
(질문의 의도를 밝혀주시면 답변에 도움이 됩니다)

--
가이드를 작성한 시점에 근거하여 답변을 드리자면, 
PK가 불변임이 보장되지 않으면 운영상 번거로움이 있기 때문입니다.
예를 들어, `(u_id, b_id)`를 PK로 만든다면 u_id, b_id가 불변값이 아니기 때문에, 해당 키값을 클라이언트에서 보관하고 있다면 문제가 됩니다.

이를 가장 쉽게 예방할 수 있는 방법은 ID 컬럼(auto-incremented)을 PK로 설정하는 것입니다.

커버링 인덱스가 필요하다면 수동으로 생성하면 됩니다.
INSERT 성능이 병목을 일으킨다면 RDBMS가 적절한 선택이 아닐 수 있습니다.

**Comment by pueue** [comment]
@namenu 
many-to-many를 연결하는 테이블을 만들려고 합니다. 
예를 들어 테이블은 외부키 컬럼(fk_1, fk_2) 2개와 정렬순서(sort_order) 컬럼으로 이루어져 있습니다. 
세 컬럼을 모두 묶어 unique key로 구성하려고 합니다.
`(fk_1, fk_2, sort_order)`를 PK로 두고, `(fk_2, fk_1, sort_order)`로 인덱스를 생성하면 어떨까 싶습니다.

**Comment by namenu** [comment]
@pueue 
해당하는 경우에도 id 컬럼을 surrogate key로 두고, 별도의 unique 인덱스를 생성하여도 문제가 없을 것 같습니다.
(역시 변할 수 있는 값이므로)
