### ISSUE TITLE
'Ridi' PHP root-level namespace

### ISSUE THREAD

**Issue by luaneyed** [ridi/style-guide#109]
이제 `Ridibooks`에 이어서 `RidiSelect`라는 namespace가 등장했습니다.
그래서 둘 모두에 속한 공통적인 것들(우리 회사에서 쓰는 PHP 코드라면 어디나 쓸 수 있을만한 것들)은 `Ridi`를 사용하는 것이 어떨지 제안드립니다.

1. 마땅히 제안할 곳이 없지만 중요한 것이라고 생각되어서 여기서 확인 받습니다.
2. style-guide에 PHP root-level namespace 관련 규칙이 추가되어도 좋을 것 같습니다.

---

`Ridi`를 사용할만한 곳들
- php-core
- https://github.com/ridi/php-oauth2
- https://github.com/ridi/platform-common
- https://github.com/ridi/library-php

---
(추가)

Ridi 하위에는 항상 서비스 명을 넣는 규칙도 제안드립니다. 충돌을 막을 수 있습니다.
충돌 방지가 주된 목적이기 때문에, 이 규칙을 넣을 때 **라이브러리**에만 적용하고 **프로젝트**에는 적용하지 않는 방법도 가능할 것 같습니다. (참고: [Composer Package Type](https://getcomposer.org/doc/04-schema.md#type))

- php-core -> `Ridi\Core`
- https://github.com/ridi/php-oauth2 -> `Ridi\OAuth2`
- https://github.com/ridi/platform-common -> `Ridi\Platform\Common` (상황에 따라 multiple depth로)
- https://github.com/ridi/library-php -> `Ridi\Library`

**프로젝트**도 동일 규칙을 적용한다면, 추후에 이런 식으로 통합도 가능합니다.
- `RidiBooks` -> `Ridi\Books` or `Ridi\Store`
- `RidiSelect` -> `Ridi\Select`

또는,

- `Ridi\Library\Core`
- `Ridi\Library\OAuth2`
- `Ridi\Library\Library`
- `Ridi\Project\Books`
- `Ridi\Project\Select`

이런 식으로 갈 수도 있지만 **길다**는 단점이 있습니다.

**Comment by limeburst** [comment]
리디북스는 이제 분리할 수 없는 고유명사가 되었다고 생각해 조금 거부감이 드네요.

**Comment by luaneyed** [comment]
오히려 **프로젝트는 그 이름(not ridi)을 root level로 설정한다** 라는 반대의 규칙도 생각해볼 수 있습니다.

그러나 프로젝트의 경우에는 그냥 무시하는 것도 괜찮다고 생각합니다.
리디스토리를 추가한다고 가정하면 `RidiStory`, `Ridi\Story` 등 어떻게 쓰던지 자유롭게요.

**Comment by kyungmi** [comment]
이 건은 해결이 되어서 닫힌건가요? 어떤 결론이 났는지 궁금한데요 ㅎㅎ

**Comment by luaneyed** [comment]
github comment 외에 구두 등으로 논의한 바는 없습니다.

**Comment by namenu** [comment]
이 내용은 마땅한 결론이 나지 않았습니다.

이 작업을 진행하기 위해 필요한 노력은 작지 않은데 예상되는 이득은 nice-to-have 정도의 일관성이라,
현재의 문제점과 필요성이 명확해지기 전까지는 보류하기 위해 닫았습니다.

제 2, 제 3의 @luaneyed 님이 등장한다면 논의가 계속되지 않을까요? 😃
