### ISSUE TITLE
OSS on GitLab.com

### ISSUE THREAD

**Issue by yangroro** [ridi/style-guide#112]
https://github.com/ridi/style-guide/blob/master/OSS.md#github-%EA%B4%80%EB%A6%AC
 위 가이드에 따라 리디에서 관리하는 모든 오픈소스 프로젝트는 지금 GitHub에서 호스팅중입니다. 그런데 기존 사내 프로젝트를 OSS로 전환하는 과정에서 GitLab CI/CD의 파이프라인에 묶여있는 경우가 있는데 이 경우에는 오픈소스로 전환을 하기 위해서 충분히 많은 기능을 가진 GitLab CI/CD로 만들어 놓은 파이프라인을 포기해야합니다.   
 마침 이번에 GitLab.com으로 이주하면서 GitLab에서 호스팅중인 프로젝트도 OSS로 전환할 여지가 생겼는데요. GitLab에서도 OSS 프로젝트 호스팅을 하면 좋을 것 같습니다. 
아니면 GitLab.com의 프로젝트를 GitHub로 미러링하는 것도 좋습니다.

**Comment by yangroro** [comment]
지금 store팀에서는 `crm-api`와 `user-book-worker`를 오픈소스로 전환하는걸 고려중인데 두 프로젝트 모두 GitLab CI/CD로 배포중입니다.

**Comment by freekering** [comment]
GitHub의 프로젝트를 GitLab으로 미러링하여 GitLab CI/CD 를 사용하는 방법도 있습니다.

**Comment by yangroro** [comment]
그것도 좋은 방법 같습니다. 그 역순은 생각 못했는데 그것도 좋겠네요.

**Comment by antiline** [comment]
저희팀 Account 서버 때문에 gltlab.com 이전시 알아봤습니다.
아래 이유들 때문에 그냥 Travis 사용하고 있습니다.

1. GItLab -> GitHub 으로 미러링
- GitHub이 사용자가 많고 홍보효과가 더 큼
- 관련된 툴이 적절한게 없어서 만들어야 함
- CI 환경설정이 오픈되는지 아니면 맴버만 볼 수 있는지 확인 못함

2. GitHub -> GitLab 
- 무료 플랜으로는 동기화가 느림
- 실시간 보장하는 유료플랜은 너무 비쌈

**Comment by antiline** [comment]
방금 추가적으로 찾아보니 https://about.gitlab.com/solutions/open-source/
이런게 있는데, GitHub-> GitLab 미러링도 오픈소스로 보고 Gold plan 을 해주는지 모르겠습니다.

**Comment by yangroro** [comment]
말씀해주신건 조금 힘들 것으로 예상되네요. 
2, 3은 현실적으로 고르기 힘들겠네요. 
1.은 단점이 있긴 하지만 말씀해주신 환경 설정의 권한 문제를 확인하고 나면 문제는 없을 것 같습니다. 
말씀하신 `GitHub이 사용자가 많고 홍보효과가 더 큼`을 포기해야하지만요...

**Comment by antiline** [comment]
3번의 유료 플랜이 아니면 `GitHub이 사용자가 많고 홍보효과가 더 큼` 를 버리고 1번으로 가는게 저는 좋다고 생각합니다.

**Comment by yangroro** [comment]
@antiline 저도 같은 생각입니다. 그래서 GitLab.com 에서도 호스팅 할지에 대한 결정이 필요하네요. 만약 1번으로 간다면 `사내에서 개발하는 오픈소스는 GitHub에서 관리하고 있습니다.` 가이드에도 수정이 필요해보입니다.

**Comment by antiline** [comment]
@namenu 
의견 바랍니다.

**Comment by namenu** [comment]
GitLab은 오픈소스 커뮤니티로서 아직은 위상이 부족하므로 가이드에서 굳이 언급하는 것은 시기적으로 이르다 생각합니다. 또한 GitLab을 인정하지 않는다는 것은 그곳에 `공개된 저장소`라 할지라도 `관리되는 오픈소스`라고 하기는 부족한 점이 있다는 것과 같습니다.

따라서, 아래의 선택지가 있을 것 같습니다.

1. CI가 GitHub에서 동작하도록 수정
2. GitHub에 수동/자동 미러를 구축하고 미러임을 명시
  - 예) https://github.com/gitlabhq/gitlabhq
3. GitLab에서 공개상태로 두되 특별히 언급 안함

**Comment by luaneyed** [comment]
저는 현우님이 말씀하신 것 중 3을 취해도 충분히 좋다고 생각합니다.

1. [보안에 도움이 됩니다.](https://github.com/ridi/style-guide/blob/master/OSS.md#%EC%9E%A5%EC%A0%90)

2. packagist를 사용할 수 있다는 것을 저는 장점으로 생각합니다.

**Comment by yangroro** [comment]
자동 미러를 별다른 수고 없이 간단한 설정만으로도 구축이 가능하다면 좋겠지만 현재로썬 그건 힘들어보여서 일단 스토어팀에서 공개하고자 하는 프로젝트들은 3을 취하겠습니다. 
나중에라도 미러링을 할 수 있다면 그렇게 하고요.
그럼 이 이슈는 여기서 마무리 할게요!
