### ISSUE TITLE
JWT 토큰 서명에 ES256 알고리즘 지원

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#120]
현재 사용되는 토큰에서 공개키의 크기가 payload의 4배 이상으로 쿠키의 크키 또한 불필요하게 비대함.

JWT 스펙에서는 비대칭키 알고리즘으로 RS256과 함께 ES256 방식을 권장하고 있으나[^1],
최초 가이드 작성 당시(#72) 라이브러리가 미성숙한 상태임을 감안하여 RS256만을 채택하였음.

여전히 내부적으로 사용중인 라이브러리 일부는 지원이 되지 않지만 (예: firebase/php-jwt) 내부 가이드에서 ES256을 허용하지 못할 이유는 없다고 판단됨.

[^1]: https://tools.ietf.org/html/rfc7518#page-6

**Comment by antiline** [comment]
- https://jwt.io/ 에 보면 PHP의 다른 라이브러리들은 지원하고 있음
- http2 통신이면 헤더 압축으로 인해 쿠키 사이즈 부담이 적음

토큰은 여러 방식이 혼용 되기 어려운데 RS256을 더 이상 사용하지 않고 ES256으로 바꾸기 위한 목적인거죠?
`ES256을 허용` 이라고 하셔서 목적이 무엇인지 잘 모르겠습니다.

**Comment by namenu** [comment]
@antiline 토큰 암호화 타입으로 RS256 | ES256 두 가지를 허용하자는 취지입니다.
(마치 서버에서 HTTP/1.1 과 HTTP/2를 모두 허용하는 것과 비슷하게)

**Comment by antiline** [comment]
그러면 `RS256 && ES256` 인거죠? 둘다 지원해야 한다.

**Comment by namenu** [comment]
https://github.com/ridi/style-guide/pull/122
