### ISSUE TITLE
내부 서비스간 인가에서 "sub"를 지정할 수 없는 경우

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#121]
https://github.com/ridi/style-guide/blob/f9c2c0cd9ef152726165a6421cb6ebc1eb8dfd05/API.md#%EC%8B%A0%EB%A2%B0%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8A%94-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-%EC%9D%B8%EA%B0%80inter-service-authorization

현재 "sub"에 리디북스 핸들(u_id)를 넘기고 추가적으로 불변값인 "u_idx"를 지정할 수 있게 되어있습니다.
상황에 따라 리디북스 핸들을 알 수 없기 때문에 u_idx가 지정되어 있으면 "sub"를 무시하도록 가이드가 수정되어야 합니다.

**Comment by antiline** [comment]
이건 `내부 서비스간의 SSO`가 아니라 `JWT 서명`내용인건가요??

https://github.com/ridi/style-guide/blob/f9c2c0cd9ef152726165a6421cb6ebc1eb8dfd05/API.md#%EB%82%B4%EB%B6%80-%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B0%84%EC%9D%98-sso

**Comment by namenu** [comment]
@antiline 내부 서비스간의 SSO가 맞습니다. 제가 URL 링크를 잘 못 달았네요. 코멘트로 링크해주신 내용이 옳습니다1

**Comment by namenu** [comment]
#122
