### ISSUE TITLE
"MariaDB(MySQL) - DDL, DML 작성 규칙" 글자 깨짐

### ISSUE THREAD

**Issue by jaeyeonling** [ridi/style-guide#123]
안녕하세요.

Language 카테고리에 있는 "MariaDB(MySQL) - DDL, DML 작성 규칙" 글의 글자가 깨져서 보입니다.

https://ridi.github.io/style-guide/MariaDB(MySQL).md 에서 .md 지우고 접속하면 잘 보이네요.

좋은 글 공개해주시는 오픈 소스 정신 감사합니다 :)

**Comment by namenu** [comment]
깨진 링크를 수정하였습니다. 감사합니다!
