### ISSUE TITLE
API Addressing 관련

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#22]
현재 RESTful API 작성 가이드에는 아래와 같은 내용이 있습니다.
```
첫 번째 Path Segment 는 서비스명으로 시작한다.
예) api.ridibooks.com/search/
```
이는 API Gateway (api.ridibooks.com) 을 염두에 두고 정했던 것입니다. 그러나 팀이 cross functional 형식으로 운영되는 현재 상황에는 잘 맞지 않는 부분이 있습니다.

**1. 지금처럼 API Gateway 를 사용할 경우**
- 장점:
  - 유연하고 일관성있는 API 설계 가능
- 단점:
  - 오너쉽에 따른 배포 문제
  - 성능 문제
  - 고가용성 문제

**2. API Gateway 를 사용하지 않을 경우** (my-service.api.ridibooks.com)
- 장점:
  - 1번 방식의 단점을 극복할 수 있음
- 단점:
  - HTTPS 프로토콜 사용이 어려움
  - Public API 노출시 일관성이 떨어짐
  - DNS 관리 비용 증가

각각의 경우에 대한 의견을 취합하여 우리 상황에 맞는 의사결정을 하고자 합니다.

**Comment by kyungmi** [comment]
AWS에서 제공하는 API Gateway(https://aws.amazon.com/ko/api-gateway/)를 사용하면,

- 고가용성 확보
- AWS 내에 있는 API와 레거시에 있는 API를 라우팅 가능
- SDK를 자동 생성(플랫폼 별)

이런 기능을 제공해 준다고 하네요.

**Comment by namenu** [comment]
슬랙에서 나왔던 Apigee를 포함하여 외부 API Gateway 솔루션과 우리의 니즈가 얼마나 부합하는지를 검토해 보는것이 우선이겠군요. 내부 asana 이슈로 등록하고 진행하겠습니다!

**Comment by kyungmi** [comment]
넵 ㅎ Apigee 같은 경우는 이 동영상(https://www.youtube.com/watch?v=WaifuBpP11U&list=UUH7xyou6RXO8PKwMZ4nQ64Q)을 보면 대충 사용법이 감이 오는 것 같아요.

다양한 엔드포인트들을 프록시의 특정 path로 매핑하는 방식은 굉장히 직관적인 것 같고,
여러 개의 policy 블록을 조합해서 요청 플로우를 구성하는 방식이 인상적이네요.

쓰게 되면 API 설계가 리소스 단위로 어느 정도 틀이 잡힌 상태로 구성되는거 같은데, 이게 걸림돌이 될 지, 도움이 될지는 잘 모르겠어요.

**Comment by namenu** [comment]
당시 API Gateway의 이해도가 부족한 상태에서 등록된 이슈인데,
단점으로 나열된 대부분의 항목들은 SaaS를 이용하면 손쉽게 극복 가능한 것으로 판명되었습니다.

다만 오너쉽에 따른 배포 문제는 여전히 남아있는데, 이는 독립적으로 해결해야 할 문제이므로 이 이슈는 close 하겠습니다.
