### ISSUE TITLE
IDE 에서 새로운 파일 생성시 author 주석이 달리지 않게

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#32]

**Comment by jihungen** [comment]
IntelliJ 같은 경우는 default가 author 주석이 달려서, 코딩 가이드에 넣으면 좋을 것 같습니다. 하지만, README.md의 Language 중에 해당이 되는 언어가 없는 것 같습니다. 혹 필요하다면 다음을 고치면 됩니다:
Preference => Editor => File and Code Templates => Includes tab => File Header

PyCharm 같은 경우는 다행히 default에 author 주석이 별도로 없습니다.

PhpStorm도 IntelliJ와 같이 author 주석이 달렸던 것으로 기억하는데, 지금 PHP를 사용하지 않고 trial 기간도 지나서 확인할 방법이 없습니다 ^^;;

**Comment by namenu** [comment]
@jihungen IntelliJ는 추후 데이터팀에서 Scala 코딩 스타일 가이드를 만들어 주시고 거기에 추가하면 되겠습니다!
