### ISSUE TITLE
UI 텍스트 가이드 높임말 사용 관련 내용

### ISSUE THREAD

**Issue by gyujincho** [ridi/style-guide#41]
@jaeminbae UI 텍스트 가이드를 조금씩 반영하고 있는데요, 
아래 문장들을 수정 중에 높임말 사용에 대한 내용이 없어서 이슈를 등록합니다. 

```
- 다운로드할 책을 선택하세요. 
- 삭제하실 도서를 선택해주세요. 
- 책은 구매 목록에서 영구히 삭제되며 다시 구매해야 이용할 수 있습니다. 그래도 삭제하시겠습니까? 
- 기간만료된 책은 다운로드 하실 수 없습니다.
```

가이드 내의 예시들을 살펴보면

**1. 지금 바로 사용자가 취해야 하는 행동이 어미에 오는 경우** 에는 높임말을 사용하고

```
- 책을 삭제하시겠습니까?
- 결제를 취소하시겠습니까?
- 키워드를 다시 선택해주세요.
```

**2. 직접 행동을 요청하거나 되묻는 어미가 아닌 경우** 에는 높임말을 사용하지 않는 것 같은데요.

```
- 공인인증서가 없어도 간편하게 이용할 수 있습니다.
- ‘책장 목록에서 원하는 책장을 선택해주세요.’에서 ‘원하는’
- ‘매월 1일 자동충전 설정하고 더블포인트 적립 놓치지 마세요!’에서 ‘설정하고’
```

위와 같이 생각하고 추가로 '책'을 통일하면 수정된 문장은 아래와 같습니다. 

```
- 다운로드할 책을 선택하세요. > 다운로드할 책을 선택해주세요.
- 삭제하실 도서를 선택해주세요. > 삭제할 책을 선택해주세요.
- 책은 구매 목록에서 영구히 삭제되며 다시 구매해야 이용할 수 있습니다. 그래도 삭제하시겠습니까? > 유지
- 기간만료된 책은 다운로드 하실 수 없습니다. > 기간 만료된 책은 다운로드할 수 없습니다.
```

위와 같이 구분하는게 맞을지, 그리고 높임말 관련 내용을 추가하면 어떨지 검토 부탁드립니다.

**Comment by gyujincho** [comment]
추가: 띄어쓰기 사전에는 이런 예시들이 있네요.

```
- 모바일 뷰어에서는 읽으실 수 있습니다.
- 최대 1000글자까지 선택하실 수 있습니다.
```

**Comment by jaeminbae** [comment]
@gyujincho 의견 감사합니다. 
'높임말'은 하십시오체/해요체 등 어조를 포괄하는 내용이라 **'-시-' 어미 사용 가이드**로 지칭하도록 하겠습니다.
규진님이 정리해주신 게 맞는 것 같네요. 

**1. 당장 사용자에게 행동을 요구하는 경우, '-시-' 어미를 문장의 마지막 용언에만 사용함**
- '-시-' 어미 사용으로 사용자 부담을 감소시킴
- '-시-' 어미는 많을수록 자연스럽지 않고 오히려 예의바른 느낌이 없어지므로 마지막에만 사용함

**2. 직접 행동을 요청하는 경우가 아니면 '-시-'어미를 사용하지 않음**
- '-시-' 어미가 없더라도 충분히 정중한 느낌을 전달함

최종적으로 정해지면 띄어쓰기 사전에 있는 예시들은 수정하도록 하겠습니다.

**Comment by jaeminbae** [comment]
해당 내용 반영되어 이슈 닫겠습니다.
https://github.com/ridi/style-guide/blob/master/UI/Text.md
