### ISSUE TITLE
'구매'와 '결제' 단어 구분

### ISSUE THREAD

**Issue by hannahsung** [ridi/style-guide#45]
**구매 (purchase)**
* 물건 따위를 사들이다.
* ex. 상품을 구매하다.
* ex. 몇 집이 공동으로 물건을 싼값에 구매했다.
* ex. 3만 원 이상 구매하시면 배송료가 무료입니다.

**결제 (payment)**
* <경제> 증권 또는 대금을 주고받아 매매 당사자 사이의 거래 관계를 끝맺다.
* ex. 숙박비를 카드로 결제하다.
* ex. 그 회사는 어음을 결제하지 못해 부도 처리가 됐다.
* ex. 신용카드로 결제하다.

**구매: 물건을 사는 행위
결제: 물건을 사기 위한 수단, 내역, 지불하는 행위**

'구매'와 '결제' 단어 구분을 이렇게 하면 어떨까 합니다.

**Comment by jaeminbae** [comment]
@hannahsung 넵 좋습니다. UI 텍스트 사전 스프레드시트에 '상황별 표현'시트에 추가하면 어떨까 합니다.
+ '구입'의 사용 여부도 같이 고민해서 추가하면 어떨까요?

**Comment by hannahsung** [comment]
'구입'도 생각해봤는데, '구매'로 통일할 수 있을 것 같습니다.
ex. 자유이용권은 **구입** 후 바로 이용 기간이 적용됩니다. → 자유이용권은 **구매** 후 바로 이용 기간이 적용됩니다.

**Comment by jaeminbae** [comment]
넵 저도 좋은 것 같습니다만, 구입, 구매 관련해서 슬랙에서 뷰어팀과 스토리팀 의견을 들어보고 결정하도록 할게요~

**Comment by hannahsung** [comment]
넵 알겠습니다~!

**Comment by jaeminbae** [comment]
논의 완료되어 UI 텍스트 사전에 추가하였습니다. 이슈 닫겠습니다.
