### ISSUE TITLE
AWS API Gateway의 제약 사항에 따른 검토

### ISSUE THREAD

**Issue by freekering** [ridi/style-guide#52]
#22 의 연장선상에 있는 문제입니다.

실제로 api.ridibooks.com 에 대해 AWS API Gateway를 적용했을 때 경로 맵핑을 최상위 경로 요소까지만 지원하는 제약으로 인해 각 service별로 API를 구성하고 여러 팀이 동일한 API를 관리해야 하는 상황이 발생하게 됩니다. 이 경우 어떤 end point가 어느 팀에 귀속되는지 파악이 어렵고 관리상의 실수로 타 팀 end point를 건드리게 되거나 하는 문제가 발생할 수 있습니다. 이에 따라

- 최상위 API Gateway에 대한 수정 권한을 최소한의 인원에게만 부여하거나
- 웹 콘솔을 사용하지 않고 Terraform 등의 도구를 이용하여 배포하도록 강제하거나
- 혹은 최악의 경우 addressing 방식을 고치거나 다른 API Gateway를 검토하거나

하는 등의 대책 마련이 필요해 보입니다.

**Comment by kyungmi** [comment]
여러 팀에서 하나의 API를 함께 수정한다고 한다면 API Gateway에서 배포 작업이 API 단위로 이루어진다는 점도 문제가 될 수 있을 것 같습니다.
