### ISSUE TITLE
[PHP] 들여쓰기에 TAB 문자 금지

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#61]
현재의 들여쓰기 기준은 프로젝트에 따라 space(4) 혹은 tab 문자를 모두 허용하고 있습니다.
https://github.com/ridi/style-guide/tree/master/PHP#수정-psr-2

불필요한 diff가 발생할 것이 우려되어 추가한 규칙이지만, tab으로 시작하는 신규 프로젝트도 많이 생기면서 프로젝트마다 IDE 설정을 달리 해야 하는 불편함이 생겼습니다.

이에 해당 규칙을 없애고 PSR-2 기준으로 space(4)로 통일하는 것을 제안합니다.

PS. diff 문제는 `git blame -w` 등으로 우회할 수 있습니다.

**Comment by sangguk2** [comment]
tab을 몇 space로 보여줄지가 editor나 viewer마다 다른 경우가 있어서, 저는 space 자체가 더 좋다고 봅니다.

**Comment by limeburst** [comment]
스토어팀 백엔드파트는 만장일치로 예외 조항을 없애는 것이 좋다는 의견입니다.

**Comment by earus** [comment]
스토어팀 코드에 반영 및 배포 완료했습니다.

**Comment by namenu** [comment]
관련하여 스타일 가이드도 변경되었습니다.
https://github.com/ridi/style-guide/commit/69069b01cdfa55ad4e263349899b3d47683e1509
