### ISSUE TITLE
TypeScript 코딩 스타일 가이드 추가

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#70]

**Comment by luaneyed** [comment]
https://github.com/ridi/tslint-config
위 링크를 남겨놓는 것으로 충분하지 않을까요?

**Comment by namenu** [comment]
tslint가 어떻게 결정된 것인지 맥락은 조금 부족하지만, 링크가 없는 것 보다는 나은 것 같아서 우선 추가했습니다.
