### ISSUE TITLE
쌍점(콜론)에 대한 텍스트 가이드 추가

### ISSUE THREAD

**Issue by incleaf** [ridi/style-guide#78]
> 쌍점의 앞은 붙여 쓰고 뒤는 띄어 쓴다.

국립국어원의 [한글 맞춤법 - 쌍점](https://www.korean.go.kr/front/page/pageView.do?page_id=P000197&mn_id=30) 페이지에서 가져온 규정입니다.

현재 이 맞춤법을 지키지 않는 경우가 종종 보이곤 하는데 아래 내용을 [텍스트 가이드](https://github.com/ridi/style-guide/blob/master/UI/Text.md)에 추가하는 건 어떨까요?

## 쌍점(콜론)을 사용하는 경우
[쌍점 표기법](https://www.korean.go.kr/front/page/pageView.do?page_id=P000197&mn_id=30)에 맞추어 적습니다.

> x: `적립 리디포인트 : 13원`
> o: `적립 리디포인트: 13원`

**Comment by namenu** [comment]
https://github.com/ridi/style-guide/blob/master/UI/Text.md#%EC%BD%9C%EB%A1%A0%EC%9D%84-%ED%91%9C%EA%B8%B0%ED%95%A0-%EA%B2%BD%EC%9A%B0

**Comment by namenu** [comment]
기존에도 국립국어원 내용을 기본으로 한다는 원칙이 있지만, 자주 틀리는 표현이므로 가이드에 추가하였습니다.
의견 감사합니다!
