### ISSUE TITLE
[JavaScript] npm 패키지 관리 방법 추가

### ISSUE THREAD

**Issue by namenu** [ridi/style-guide#82]
아래 내용을 참고하여 npm에 대한 내용을 추가할 것

1. https://github.com/ridi/style-guide/tree/master/PHP#%EC%9D%98%EC%A1%B4%EC%84%B1-%EA%B4%80%EB%A6%AC-composer

2. https://github.com/ridi/style-guide/tree/master/Python#%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B4%80%EB%A6%AC

**Comment by krazijames** [comment]
참고: https://docs.npmjs.com/misc/developers
